### PR TITLE
Mediawiki 1.29

### PR DESCRIPTION
**Pull request by Silex**
Hello,

This is *almost* working.

Basically, upgrades to Mediawiki current release 1.29. I also made other changes that seemed obvious to me, feel free to discuss.

We just need to figure out https://www.mediawiki.org/wiki/Topic:Txbtrd36djyaitfm... but basically, at the moment restarting the web container works (the first time it makes the error and the second time it works).

Hum, I found this: https://gerrit.wikimedia.org/r/#/c/364289/

Looks like it's already fixed and we need to wait? I'm unfamiliar with the mediawiki workflow.

### CODE REVIEW

**Review by pastakhov — APPROVED** [review]
thanks for fixing it

**Review by pastakhov — COMMENTED** [review]
my SQL image runs mysql_upgrade when mysql version changed, there is no other difference...
And I am sure this feature is helpful...

**Comment by pastakhov** [comment]
oh, I wanted to merge only `Fix typo` patch... 
I don't want use Standard MySQL image since one does not run mysql_upgrade.
And please make  the`Use MediaWiki 1.29` as a separated request. 
so I can't merge it all at once

**Review by pastakhov — CHANGES_REQUESTED** [review]
please make one as a separate requests

**Comment by Silex** [comment]
Alright I let the 1.29 commit only. Let's wait a bit for the gerrit to resolve.

I also have another PR incoming that adds PDF export, it was working in 1.28 but it's not working with 1.29, are you good with restbase? I have a route error and there's so many components that I'm a bit lost.

Also, sometimes I notice the cache is wrong (varnish?) and I have to edit the pages twice.

**Comment by pastakhov** [comment]
does PDF export use restbase? I don't meet this in documentation...

> Also, sometimes I notice the cache is wrong

please provide the error messages

**Comment by Silex** [comment]
For the PDF export I'm using https://www.mediawiki.org/wiki/Extension:ElectronPdfService

In 1.28, it was using the Electron service directly and in 1.29 it tries to use it through restbase.

About the varnish problem, I'll make a separate issue.

**Comment by pastakhov** [comment]
Yes ElectronPdfService works via a RESTBase API endpoint.
It requires the msokk/electron-render-service docker container and change configuration in restbase.
Sorry, I am very busy now with other tasks. I'll make it later, maybe in Jan.

**Comment by Silex** [comment]
Oh well I already have all this, let me create another PR so we can discuss why it does not work with 1.29.

**Comment by Silex** [comment]
Okay, for me we are good to go.

Only need to wait for https://gerrit.wikimedia.org/r/#/c/364289/ to solve itself.

**Comment by Silex** [comment]
@pastakhov: ping me when you reviewed #9, #11 and #13, to think about the best merge strategy.

**Comment by pastakhov** [comment]
@Silex, Sorry for delay and thanks for the patches, I got busy... 
so much events before new year, let's review patches in Jan.
thanks for your patience :)

**Comment by Silex** [comment]
A'ight :wink:

**Comment by Silex** [comment]
Okay I rebased this mediawiki 1.29 PR, I think you can merge.

**Comment by Silex** [comment]
Rebased it once more :smile: 

You were supposed to merge this one then the PDF export one but it does not matter.

**Comment by pastakhov** [comment]
Hey, how about the Flow issue?

**Comment by Silex** [comment]
What is the flow issue?

**Comment by pastakhov** [comment]
https://github.com/pastakhov/compose-mediawiki-ubuntu/pull/9#issuecomment-347791653
> Okay, for me we are good to go.
> Only need to wait for https://gerrit.wikimedia.org/r/#/c/364289/ to solve itself.

**Comment by Silex** [comment]
Well, as I said at the moment all you have to do is restart the container... thus this should be solved by the `restart: always` policy.

Also that only happens the first time when the db initializes... and given I didn't test since a while maybe this is already fixed on the 1.29 branch?

**Comment by pastakhov** [comment]
Silex, thanks

**Comment by Silex** [comment]
:+1:

**Pull request merged**
